using System.Globalization;
using System.Text;
using Platform.Conformance.Harness.Catalogue;

namespace Platform.Conformance.Report;

/// <summary>Renders the merged catalogue as <c>docs/capabilities.md</c>: a summary and one table per owner. The output is deterministic.</summary>
internal static class CatalogueMarkdownRenderer
{
    /// <summary>Renders the catalogue.</summary>
    /// <param name="catalogue">The merged catalogue.</param>
    public static string Render(CapabilityCatalogue catalogue)
    {
        ArgumentNullException.ThrowIfNull(catalogue);
        var capabilities = catalogue.Capabilities;
        var text = new StringBuilder();
        text.AppendLine("<!-- Generated by `Platform.Conformance.Report render-catalogue` from catalogue/capabilities.yaml and catalogue/capabilities.d/*.yaml. Edit the catalogue, not this file. -->");
        text.AppendLine("# Platform capabilities");
        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"The catalogue lists {capabilities.Count} capabilit{(capabilities.Count == 1 ? "y" : "ies")}: {capabilities.Count(capability => capability.Live)} proven by live tests, {capabilities.Count(capability => !capability.Live)} offline, {capabilities.Count(capability => capability.Destructive)} destructive. Every capability names the tests that prove it, and `CatalogueConsistencyTests` keeps the catalogue and the tests one-to-one.");
        text.AppendLine();
        text.AppendLine("| Owner | Capabilities | Live | Offline | Destructive |");
        text.AppendLine("|---|---:|---:|---:|---:|");
        var owners = capabilities.GroupBy(capability => capability.Owner).OrderBy(group => group.Key).ToList();
        foreach (var owner in owners)
        {
            text.AppendLine(CultureInfo.InvariantCulture, $"| [{owner.Key.ToYaml()}](#{owner.Key.ToYaml()}) | {owner.Count()} | {owner.Count(capability => capability.Live)} | {owner.Count(capability => !capability.Live)} | {owner.Count(capability => capability.Destructive)} |");
        }

        text.AppendLine();
        foreach (var owner in owners)
        {
            text.AppendLine(CultureInfo.InvariantCulture, $"## {owner.Key.ToYaml()}");
            text.AppendLine();
            text.AppendLine("| ID | Capability | Tier | Proof | Design | Observed by | Tests |");
            text.AppendLine("|---|---|---|---|---|---|---|");
            foreach (var capability in owner.OrderBy(entry => entry.Id, StringComparer.Ordinal))
            {
                text.AppendLine(CultureInfo.InvariantCulture, $"| {capability.Id} | {MarkdownText.Cell(capability.Statement, 1000)} | {capability.Tier.ToYaml()} | {Proof(capability)} | {MarkdownText.Cell(capability.Adr, 500)} | {MarkdownText.Cell(capability.ObservedBy, 1000)} | {Tests(capability)} |");
            }

            text.AppendLine();
        }

        text.AppendLine("## Sources");
        text.AppendLine();
        text.AppendLine("| File | Capabilities |");
        text.AppendLine("|---|---:|");
        foreach (var source in catalogue.Sources)
        {
            text.AppendLine(CultureInfo.InvariantCulture, $"| {MarkdownText.Code(source)} | {capabilities.Count(capability => capability.Source == source)} |");
        }

        return text.ToString();
    }

    private static string Proof(Capability capability)
    {
        if (!capability.Live)
        {
            return MarkdownText.Cell($"offline: {capability.WhyOffline}", 500);
        }

        return capability.Destructive ? "live, destructive" : "live";
    }

    private static string Tests(Capability capability) =>
        string.Join("<br>", capability.Tests.Select(test => MarkdownText.Code(ShortName(test))));

    private static string ShortName(string fullName)
    {
        var parts = fullName.Split('.');
        return parts.Length >= 2 ? $"{parts[^2]}.{parts[^1]}" : fullName;
    }
}
