apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config
images:
  - name: acrplatformi3aldz.azurecr.io/apps/sandbox/web
    newTag: "0.1.10"
  - name: acrplatformi3aldz.azurecr.io/apps/sandbox/migrator
    newTag: "0.1.10"   # written by Octopus only
