<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>Sandbox.Web</AssemblyName>
    <RootNamespace>Sandbox.Web</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sandbox.Tests" />
  </ItemGroup>

</Project>
