#!/usr/bin/env bash
# Plans and applies octopus/terraform (ADR-IR34 §11.7.2 item 6, §11.9): the P1-06 full apply on a copy of the phase 0
# preview state, and every later apply (onboarding, the re-applies after env-apply and terraform/apps/grants).
# Procedure, inputs and checks: docs/preview-octopus.md.
#
# Inputs (environment variables):
#   OCTOPUS_API_KEY   the Space Manager key of AISF-Service-Account (ADR-IR32). It reaches Terraform only through
#                     TF_VAR_octopus_api_key and TF_VAR_platform_octopus_api_key, never through an argument. An
#                     already exported TF_VAR_octopus_api_key or OCTOPUS_APIKEY is used when it is unset.
#   TF_VAR_argocd_repo_read_credential  the JSON repository credential of Argo CD (ArgoCD.RepoReadCredential). Give it
#                     on every run once it has been set: without it the plan deletes the variable, and the next
#                     env-apply that creates a cluster (the other tier, a rebuild) seeds Argo CD without a credential.
#   TFVARS            the untracked terraform.tfvars (terraform.tfvars.example lists the values)
#   STATE_FILE        a local state file outside the repository (P1-06: the copy of the preview state). Unset: the
#                     azurerm backend octopus-space.tfstate in TF_BACKEND_STORAGE_ACCOUNT (after the migration).
#   TF_BACKEND_STORAGE_ACCOUNT  <tfstate-storage-account-global>; needed without STATE_FILE and for MIGRATE_STATE=1
#   TF_BIN            Terraform 1.7 or later (default: terraform on PATH)
#   PLAN_ONLY=1       plan and check only
#   MIGRATE_STATE=1   with STATE_FILE: copy that state to the azurerm backend and stop (no plan, no apply)
#   ALLOW_DESTROY=1   let the plan check pass deletes and replacements (never needed at P1-06)
# Azure: the configuration reads identities and ingress IPs (azure.tf) and the backend is azurerm, so the shell holds
# an Azure login with read access to the subscription (ARM_* variables or az login), as for terraform/foundation.
#
# What it does:
#   1. Copies octopus/terraform to a private temporary directory; with STATE_FILE it adds a local-backend override.
#   2. terraform init, then plan with -parallelism=1 (provider 1.20.0 panicked on concurrent team creates).
#   3. Refuses the plan when it deletes or replaces anything but scoped user roles and variables, or when it deletes
#      ArgoCD.RepoReadCredential.
#   4. Applies the saved plan. When the only errors are "Provider produced inconsistent result after apply" (known
#      provider 1.20.0 behaviour for converted projects, see projects.tf), it plans, checks and applies once more:
#      Terraform has saved the new values, so the second pass converges.
# The plan file and the state hold the key; the temporary directory is private and removed on exit.

set -euo pipefail
umask 077

die() { echo "apply: $*" >&2; exit 1; }

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd -P)"
tf_source="$repo_root/octopus/terraform"
[ -d "$tf_source" ] || die "missing $tf_source"

tf_bin="${TF_BIN:-terraform}"
command -v "$tf_bin" >/dev/null 2>&1 || die "Terraform not found (TF_BIN=$tf_bin)"
command -v python3 >/dev/null 2>&1 || die "python3 is required"

plan_only="${PLAN_ONLY:-0}"
migrate_state="${MIGRATE_STATE:-0}"
allow_destroy="${ALLOW_DESTROY:-0}"

# --- Credentials: environment only ----------------------------------------------------------------------------
key="${OCTOPUS_API_KEY:-${TF_VAR_octopus_api_key:-${OCTOPUS_APIKEY:-}}}"
[ -n "$key" ] || die "set OCTOPUS_API_KEY (the Space Manager key; ADR-IR32)"
case "$key" in API-*) ;; *) die "OCTOPUS_API_KEY is not an Octopus API key (API-...)" ;; esac
export TF_VAR_octopus_api_key="$key"
export TF_VAR_platform_octopus_api_key="${TF_VAR_platform_octopus_api_key:-$key}"
unset key
export TF_IN_AUTOMATION=1

# --- Working copy -----------------------------------------------------------------------------------------------
work_dir="$(mktemp -d)"
cleanup() { rm -rf "$work_dir"; }
trap cleanup EXIT

cp "$tf_source"/*.tf "$work_dir"/
[ -f "$tf_source/.terraform.lock.hcl" ] && cp "$tf_source/.terraform.lock.hcl" "$work_dir"/

backend_args=()
if [ -n "${STATE_FILE:-}" ]; then
    state_dir="$(cd "$(dirname "$STATE_FILE")" && pwd -P)" || die "the directory of STATE_FILE does not exist"
    case "$state_dir/" in
        "$repo_root"/*) die "STATE_FILE must be outside the repository (it holds the Space Manager key)" ;;
    esac
    state_file="$state_dir/$(basename "$STATE_FILE")"
    if [ "$migrate_state" != "1" ]; then
        [ -f "$state_file" ] || echo "apply: $state_file does not exist yet; Terraform starts an empty state"
    fi
    cat > "$work_dir/backend_override.tf" <<HCL
# Generated by octopus/apply.sh: local state outside the repository.
terraform {
  backend "local" {
    path = "$state_file"
  }
}
HCL
else
    [ -n "${TF_BACKEND_STORAGE_ACCOUNT:-}" ] || die "set STATE_FILE, or TF_BACKEND_STORAGE_ACCOUNT for the azurerm backend"
    [ "$migrate_state" != "1" ] || die "MIGRATE_STATE=1 needs STATE_FILE (the state to copy)"
fi

azurerm_backend_args=(
    "-backend-config=resource_group_name=rg-platform-global"
    "-backend-config=storage_account_name=${TF_BACKEND_STORAGE_ACCOUNT:-}"
    "-backend-config=container_name=tfstate"
    "-backend-config=key=octopus-space.tfstate"
    "-backend-config=use_azuread_auth=true"
)
[ -n "${STATE_FILE:-}" ] || backend_args=("${azurerm_backend_args[@]}")

tf() { "$tf_bin" -chdir="$work_dir" "$@"; }

tf init -input=false -no-color "${backend_args[@]}" >/dev/null
echo "terraform init: done ($([ -n "${STATE_FILE:-}" ] && echo "local state $state_file" || echo "azurerm octopus-space.tfstate"))"

if [ "$migrate_state" = "1" ]; then
    [ -n "${TF_BACKEND_STORAGE_ACCOUNT:-}" ] || die "MIGRATE_STATE=1 needs TF_BACKEND_STORAGE_ACCOUNT"
    [ -f "$state_file" ] || die "$state_file does not exist"
    rm -f "$work_dir/backend_override.tf"
    tf init -input=false -no-color -migrate-state -force-copy "${azurerm_backend_args[@]}"
    echo "State copied to octopus-space.tfstate in $TF_BACKEND_STORAGE_ACCOUNT. Later runs: unset STATE_FILE."
    exit 0
fi

# --- Plan and check -------------------------------------------------------------------------------------------
tfvars_args=()
if [ -n "${TFVARS:-}" ]; then
    [ -f "$TFVARS" ] || die "TFVARS $TFVARS does not exist"
    tfvars_args=("-var-file=$(cd "$(dirname "$TFVARS")" && pwd -P)/$(basename "$TFVARS")")
fi

plan_and_check() {
    # $1: pass label. Writes $work_dir/$1.tfplan.
    local label="$1" plan_file="$work_dir/$1.tfplan"
    tf plan -input=false -no-color -parallelism=1 -var "repo_root=$repo_root" "${tfvars_args[@]}" -out="$plan_file"
    tf show -json "$plan_file" > "$work_dir/$label.json"
    ALLOW_DESTROY="$allow_destroy" python3 - "$work_dir/$label.json" "$label" <<'PY'
import json, os, sys
plan = json.load(open(sys.argv[1]))
# Deletes and replacements pass only for objects that carry no history.
replaceable = {"octopusdeploy_scoped_user_role", "octopusdeploy_variable"}
# A run without TF_VAR_argocd_repo_read_credential would delete ArgoCD.RepoReadCredential, which every env-apply
# that creates a cluster needs (terraform/tier seeds Argo CD's repository credential from it).
kept = {"octopusdeploy_variable.infrastructure_argocd_repo_read_credential[0]": "set TF_VAR_argocd_repo_read_credential"}
counts, bad = {}, []
for rc in plan.get("resource_changes", []):
    if rc.get("mode") != "managed":
        continue
    actions = rc["change"]["actions"]
    if actions == ["no-op"]:
        continue
    key = "/".join(actions)
    counts[key] = counts.get(key, 0) + 1
    if "delete" in actions and rc["type"] not in replaceable:
        bad.append(f'{rc["address"]} ({key})')
    elif actions == ["delete"] and rc["address"] in kept:
        bad.append(f'{rc["address"]} ({key}; {kept[rc["address"]]})')
moves = sum(1 for rc in plan.get("resource_changes", []) if rc.get("previous_address"))
print(f"[{sys.argv[2]}] planned: " + (", ".join(f"{k}={v}" for k, v in sorted(counts.items())) or "no changes")
      + f"; moved addresses: {moves}")
if bad and os.environ.get("ALLOW_DESTROY") != "1":
    sys.exit("apply: refusing, the plan deletes or replaces: " + ", ".join(bad) + " (ALLOW_DESTROY=1 overrides)")
PY
}

apply_plan() {
    # $1: pass label. Returns 0, or 2 when every error is an inconsistent-result error, or 1.
    local label="$1" log="$work_dir/$1.apply.log" rc=0 errors inconsistent
    tf apply -input=false -no-color -parallelism=1 "$work_dir/$label.tfplan" 2>&1 | tee "$log" || rc=$?
    [ "$rc" -eq 0 ] && return 0
    errors="$(grep -c '^Error: ' "$log" || true)"
    inconsistent="$(grep -c '^Error: Provider produced inconsistent result after apply' "$log" || true)"
    if [ "$errors" -gt 0 ] && [ "$errors" -eq "$inconsistent" ]; then
        return 2
    fi
    return 1
}

plan_and_check pass1
if [ "$plan_only" = "1" ]; then
    echo "PLAN_ONLY=1: nothing applied."
    exit 0
fi

rc=0
apply_plan pass1 || rc=$?
if [ "$rc" -eq 2 ]; then
    echo "apply: only inconsistent-result errors (provider 1.20.0); planning and applying once more."
    plan_and_check pass2
    rc=0
    apply_plan pass2 || rc=$?
fi
[ "$rc" -eq 0 ] || die "terraform apply failed (see the log above)"

tf output -no-color project_ids
tf output -no-color env_sleep_triggers
echo "Done. Next: the checks and API calls of docs/preview-octopus.md."
