# Outputs for the other layers and the operator. None is secret: no token password and no client secret
# exists in this state.
#
# Consumers:
#   terraform/build                 names only (build_inputs); it finds rg-platform-build by name
#   terraform/tier                  tier_inputs[<tier>] -> <tier>.tfvars and the runbook backend settings
#   terraform/apps/{tier,grants}    apps_inputs[<tier>], octopus_federation, conformance, platform_operators
#   octopus/terraform               octopus_inputs: account client IDs, the feed identity, the registry
#   Codefresh (P1-05)               registry.tokens: which integration or context holds each password
#   tests/platform.settings.json    conformance_settings

output "subscription" {
  description = "Tenant, subscription (resource ID and offer) and region."
  value = {
    tenant_id       = var.tenant_id
    subscription_id = lower(var.subscription_id)
    resource_id     = local.subscription_resource_id
    quota_id        = data.azurerm_subscription.current.quota_id
    location        = var.location
  }
}

output "resource_groups" {
  description = "Platform resource groups created here (name => ID), and the node groups AKS creates (name only)."
  value = {
    created               = local.rg_id
    aks_node_groups       = { for k, c in local.clusters : k => c.node_resource_group }
    per_tier              = local.rg_tier
    global                = local.rg_global
    build                 = local.rg_build
    foreign_never_touched = ["NetworkWatcherRG", "ai-model"]
  }
}

output "clusters" {
  description = "Names, groups and future resource IDs of the three clusters (created by terraform/build and terraform/tier)."
  value = {
    for k, c in local.clusters : k => merge(c, { id = local.cluster_ids[k] })
  }
}

output "registry" {
  description = "The shared registry (<acr-name>) and its token objects. Passwords are generated by CLI at P1-05 and stored only by the holder named here."
  value = {
    name                = azurerm_container_registry.this.name
    id                  = azurerm_container_registry.this.id
    login_server        = azurerm_container_registry.this.login_server
    resource_group_name = azurerm_container_registry.this.resource_group_name
    tokens = {
      for name, token in azurerm_container_registry_token.this : name => {
        id           = token.id
        scope_map    = azurerm_container_registry_scope_map.this[name].name
        repositories = local.acr_tokens[name].repositories
        access       = local.acr_tokens[name].access
        actions      = azurerm_container_registry_scope_map.this[name].actions
        holder       = local.acr_tokens[name].holder
      }
    }
  }
}

output "tfstate" {
  description = "Backend settings of every layer: account, container and keys (use_azuread_auth = true)."
  value = {
    global = {
      resource_group_name  = local.rg_global
      storage_account_name = azurerm_storage_account.tfstate["global"].name
      storage_account_id   = azurerm_storage_account.tfstate["global"].id
      container_name       = azurerm_storage_container.tfstate["global"].name
      keys = {
        foundation = "foundation.tfstate"
        build      = "build.tfstate"
        octopus    = "octopus-space.tfstate"
        app_grants = "app-grants-<app>.tfstate"
      }
    }
    nonprod = {
      resource_group_name  = local.rg_tier["nonprod"].shared
      storage_account_name = azurerm_storage_account.tfstate["nonprod"].name
      storage_account_id   = azurerm_storage_account.tfstate["nonprod"].id
      container_name       = azurerm_storage_container.tfstate["nonprod"].name
      keys = {
        tier = "tier-nonprod.tfstate"
        apps = "apps-<app>.tfstate"
      }
    }
    prod = {
      resource_group_name  = local.rg_tier["prod"].shared
      storage_account_name = azurerm_storage_account.tfstate["prod"].name
      storage_account_id   = azurerm_storage_account.tfstate["prod"].id
      container_name       = azurerm_storage_container.tfstate["prod"].name
      keys = {
        tier = "tier-prod.tfstate"
        apps = "apps-<app>.tfstate"
      }
    }
  }
}

output "backup_storage" {
  description = "Backup account per tier (<backup-storage-account-<tier>>); terraform/apps/tier adds container <app>-<env>."
  value = {
    for t in local.tiers : t => {
      name                  = azurerm_storage_account.backup[t].name
      id                    = azurerm_storage_account.backup[t].id
      resource_group_name   = azurerm_storage_account.backup[t].resource_group_name
      primary_blob_endpoint = azurerm_storage_account.backup[t].primary_blob_endpoint
      retention_days        = var.backup_retention_days
    }
  }
}

output "identities" {
  description = "Every platform identity by name: resource ID, client ID and principal (object) ID."
  value = merge(
    {
      for name, uami in azurerm_user_assigned_identity.tier : name => {
        id                  = uami.id
        client_id           = uami.client_id
        principal_id        = uami.principal_id
        resource_group_name = uami.resource_group_name
      }
    },
    {
      (azurerm_user_assigned_identity.octopus_acr_pull.name) = {
        id                  = azurerm_user_assigned_identity.octopus_acr_pull.id
        client_id           = azurerm_user_assigned_identity.octopus_acr_pull.client_id
        principal_id        = azurerm_user_assigned_identity.octopus_acr_pull.principal_id
        resource_group_name = azurerm_user_assigned_identity.octopus_acr_pull.resource_group_name
      }
    },
  )
}

output "octopus_federation" {
  description = "Octopus OIDC contract of the foundation credentials: issuer, audience and subject per identity. terraform/apps/grants uses the same issuer and audience."
  value = {
    issuer   = local.octopus_issuer
    audience = local.federation_audience
    subjects = { for identity, f in local.octopus_federations : identity => f.subject }
  }
}

output "conformance" {
  description = "sp-platform-conformance (no secret here: P1-05 creates it by CLI) and the mode of its AKS grants."
  value = {
    display_name                = azuread_application.conformance.display_name
    client_id                   = azuread_application.conformance.client_id
    application_object_id       = azuread_application.conformance.object_id
    service_principal_object_id = azuread_service_principal.conformance.object_id
    least_privilege             = var.conformance_least_privilege
  }
}

output "platform_operators" {
  description = "Group platform-operators."
  value = {
    display_name = azuread_group.platform_operators.display_name
    object_id    = azuread_group.platform_operators.object_id
    members      = var.platform_operator_object_ids
  }
}

output "provisioner" {
  description = "The principal that received the provisioner self-grants."
  value = {
    object_id = local.provisioner_object_id
  }
}

output "budgets" {
  description = "Budget status: created or skipped, and why."
  value = {
    status = local.budgets_on ? "created" : (
      var.budgets_enabled == false ? "skipped: budgets_enabled = false" : "skipped: Cost Management does not support quota ID ${data.azurerm_subscription.current.quota_id}"
    )
    names   = { for k, b in azurerm_consumption_budget_subscription.platform : k => b.name }
    amounts = var.budget_amounts
    groups  = { for k, v in local.budget_scopes : k => sort(v.groups) }
  }
}

output "role_assignments" {
  description = "Every grant made here: key => role, scope and principal. Used by the conformance tests and reviews."
  value = {
    for key, a in azurerm_role_assignment.this : key => {
      role      = local.grants[key].role
      scope     = a.scope
      principal = a.principal_id
      type      = a.principal_type
    }
  }
}

output "build_inputs" {
  description = "Names terraform/build uses (it finds rg-platform-build by name)."
  value = {
    resource_group_name = local.rg_build
    node_resource_group = local.clusters.build.node_resource_group
    cluster_name        = local.clusters.build.name
    tfstate_key         = "build.tfstate"
  }
}

output "tier_inputs" {
  description = "Per tier: what terraform/tier finds by name, plus the state backend of its runbooks."
  value = {
    for t in local.tiers : t => {
      tier                  = t
      tenant_id             = var.tenant_id
      subscription_id       = lower(var.subscription_id)
      location              = var.location
      resource_groups       = merge(local.rg_tier[t], { aks_nodes = local.clusters[t].node_resource_group })
      cluster_name          = local.clusters[t].name
      registry_login_server = azurerm_container_registry.this.login_server
      identities = {
        for role, name in local.tier_identity_names[t] : role => {
          name         = name
          id           = azurerm_user_assigned_identity.tier[name].id
          client_id    = azurerm_user_assigned_identity.tier[name].client_id
          principal_id = azurerm_user_assigned_identity.tier[name].principal_id
        }
      }
      backend = {
        resource_group_name  = local.rg_tier[t].shared
        storage_account_name = azurerm_storage_account.tfstate[t].name
        container_name       = azurerm_storage_container.tfstate[t].name
        key                  = "tier-${t}.tfstate"
        use_azuread_auth     = true
      }
      backup_storage_account_name = azurerm_storage_account.backup[t].name
    }
  }
}

output "apps_inputs" {
  description = "Per tier: what terraform/apps/tier and terraform/apps/grants need."
  value = {
    for t in local.tiers : t => {
      resource_groups             = local.rg_tier[t]
      backup_storage_account_id   = azurerm_storage_account.backup[t].id
      backup_storage_account_name = azurerm_storage_account.backup[t].name
      lifecycle_principal_id      = local.tier_principal[t].lifecycle
      eso_principal_id            = local.tier_principal[t].eso
      db_backup_principal_id      = local.tier_principal[t].db_backup
      conformance_principal_id    = local.conformance_principal
      platform_operators_id       = local.operators_principal
      registry_id                 = azurerm_container_registry.this.id
      backend = {
        resource_group_name  = local.rg_tier[t].shared
        storage_account_name = azurerm_storage_account.tfstate[t].name
        container_name       = azurerm_storage_container.tfstate[t].name
        key                  = "apps-<app>.tfstate"
        use_azuread_auth     = true
      }
    }
  }
}

output "octopus_inputs" {
  description = "Values for octopus/terraform: the lifecycle accounts azure-platform-lifecycle-<tier> and the feed acr-apps (OIDC)."
  value = {
    tenant_id       = var.tenant_id
    subscription_id = lower(var.subscription_id)
    audience        = local.federation_audience
    lifecycle_accounts = {
      for t in local.tiers : "azure-platform-lifecycle-${t}" => {
        environment = "infra-${t}"
        client_id   = azurerm_user_assigned_identity.tier["id-platform-lifecycle-${t}"].client_id
        subject     = local.octopus_federations["id-platform-lifecycle-${t}"].subject
      }
    }
    feed_acr_apps = {
      feed_uri  = "https://${azurerm_container_registry.this.login_server}"
      client_id = azurerm_user_assigned_identity.octopus_acr_pull.client_id
      subject   = local.octopus_federations["id-octopus-acr-pull"].subject
    }
  }
}

output "conformance_settings" {
  description = "Azure values of tests/platform.settings.json, in its shape (keys AzureSubscriptionId, AzureTenantId, RegistryLoginServer and Tiers). The client ID and secret of sp-platform-conformance come from Codefresh context platform-conformance (AZURE_CLIENT_ID, AZURE_CLIENT_SECRET)."
  value = {
    AzureSubscriptionId = lower(var.subscription_id)
    AzureTenantId       = var.tenant_id
    RegistryLoginServer = azurerm_container_registry.this.login_server
    Tiers = {
      build = {
        ResourceGroup  = local.clusters.build.resource_group_name
        ClusterName    = local.clusters.build.name
        ResourceGroups = sort(local.budget_scopes.build.groups)
      }
      nonprod = {
        ResourceGroup  = local.clusters.nonprod.resource_group_name
        ClusterName    = local.clusters.nonprod.name
        ResourceGroups = sort(local.budget_scopes.nonprod.groups)
      }
      prod = {
        ResourceGroup  = local.clusters.prod.resource_group_name
        ClusterName    = local.clusters.prod.name
        ResourceGroups = sort(local.budget_scopes.prod.groups)
      }
    }
    ForeignResourceGroups  = ["NetworkWatcherRG", "ai-model"]
    TfstateStorageAccounts = { for k, a in azurerm_storage_account.tfstate : k => a.name }
    BackupStorageAccounts  = { for k, a in azurerm_storage_account.backup : k => a.name }
    Budgets                = { for k, v in local.budget_scopes : k => v.name }
  }
}
