# Outputs consumed by the next layers (§7.10): identity IDs and client IDs, subnet IDs, private
# DNS zone IDs, ACR ID, workspace ID and SQL admin group object IDs. None is secret.
#
# Consumers:
#   terraform/environment        environment_inputs[<class>] -> <class>.tfvars (by pull request)
#   octopus/terraform            identities["id-octopus-deploy-<env>"], ["id-env-lifecycle-<class>"]
#                                and ["id-octopus-acr-pull"] client IDs for the OIDC accounts/feed
#   argocd/**, gitops/**         client IDs for azure.workload.identity/client-id annotations
#                                (<client-id-of-<uami name>>, ADR-IR7) and
#                                argocd_sso_client_id (<argocd-sso-app-client-id>)

locals {
  all_identities = merge(
    { for k, v in azurerm_user_assigned_identity.octopus_deploy : v.name => v },
    { for k, v in azurerm_user_assigned_identity.env_lifecycle : v.name => v },
    { (azurerm_user_assigned_identity.octopus_acr_pull.name) = azurerm_user_assigned_identity.octopus_acr_pull },
    { for k, v in azurerm_user_assigned_identity.aks_controlplane : v.name => v },
    { for k, v in azurerm_user_assigned_identity.aks_kubelet : v.name => v },
    { for k, v in azurerm_user_assigned_identity.eso_platform : v.name => v },
    { for k, v in azurerm_user_assigned_identity.kyverno : v.name => v },
    { for k, v in azurerm_user_assigned_identity.workorders_app : v.name => v },
    { for k, v in azurerm_user_assigned_identity.workorders_eso : v.name => v },
    { for k, v in azurerm_user_assigned_identity.workorders_migrator : v.name => v },
  )
}

output "identities" {
  description = "Every managed identity by contract name: resource ID, client ID and principal (object) ID."
  value = {
    for name, uami in local.all_identities : name => {
      id           = uami.id
      client_id    = uami.client_id
      principal_id = uami.principal_id
    }
  }
}

output "resource_group_ids" {
  description = "Resource group IDs by name."
  value       = { for name, rg in azurerm_resource_group.this : name => rg.id }
}

output "subnet_ids" {
  description = "Subnet IDs per class."
  value = {
    for c in local.classes : c => {
      aks_nodes         = azurerm_subnet.aks_nodes[c].id
      private_endpoints = azurerm_subnet.private_endpoints[c].id
    }
  }
}

output "private_dns_zone_ids" {
  description = "Private DNS zone IDs per class."
  value = {
    for c in local.classes : c => {
      sql       = azurerm_private_dns_zone.this["${c}-sql"].id
      key_vault = azurerm_private_dns_zone.this["${c}-key_vault"].id
    }
  }
}

output "acr_id" {
  description = "ACR resource ID."
  value       = azurerm_container_registry.this.id
}

output "acr_login_server" {
  description = "ACR login server (<acr-name>.azurecr.io)."
  value       = azurerm_container_registry.this.login_server
}

output "acr_tokens" {
  description = "Repository-scoped tokens to back the Codefresh registry integrations. Passwords are generated by a person (docs/runbooks/credential-rotation.md)."
  value = {
    for name, token in azurerm_container_registry_token.codefresh : name => {
      id                   = token.id
      registry_integration = local.acr_tokens[name].integration
      repositories         = local.acr_tokens[name].repositories
    }
  }
}

output "log_analytics_workspace_id" {
  description = "log-workorders resource ID."
  value       = azurerm_log_analytics_workspace.this.id
}

output "sql_admin_groups" {
  description = "SQL Entra admin group per class."
  value = {
    for c, g in azuread_group.sql_admins : c => {
      display_name = g.display_name
      object_id    = g.object_id
    }
  }
}

output "argocd_sso_client_id" {
  description = "Client ID of <argocd-sso-app>, for oidc.config and the argocd-server service-account annotation."
  value       = azuread_application.argocd_sso.client_id
}

output "tfstate" {
  description = "Backend settings for both layers (WorkOrders Infrastructure variables Terraform.*)."
  value = {
    resource_group_name  = azurerm_resource_group.this[local.rg_shared].name
    storage_account_name = azurerm_storage_account.tfstate.name
    container_name       = azurerm_storage_container.tfstate.name
    foundation_key       = "foundation.tfstate"
    environment_keys     = { for c in local.classes : c => "environment-${c}.tfstate" }
  }
}

output "environment_inputs" {
  description = "Values for terraform/environment/<class>.tfvars, keyed by class. Copy them into the untracked tfvars used by the env-plan and env-apply runbooks."
  value = {
    for c in local.classes : c => {
      cluster                      = c
      aks_controlplane_identity_id = azurerm_user_assigned_identity.aks_controlplane[c].id
      aks_kubelet_identity_id      = azurerm_user_assigned_identity.aks_kubelet[c].id
      aks_nodes_subnet_id          = azurerm_subnet.aks_nodes[c].id
      private_endpoints_subnet_id  = azurerm_subnet.private_endpoints[c].id
      private_dns_zone_ids = {
        sql       = azurerm_private_dns_zone.this["${c}-sql"].id
        key_vault = azurerm_private_dns_zone.this["${c}-key_vault"].id
      }
      log_analytics_workspace_id = azurerm_log_analytics_workspace.this.id
      sql_admin_group = {
        display_name = azuread_group.sql_admins[c].display_name
        object_id    = azuread_group.sql_admins[c].object_id
      }
      workload_identity_ids = {
        for e in local.class_envs[c] : e => {
          app = azurerm_user_assigned_identity.workorders_app[e].id
          eso = azurerm_user_assigned_identity.workorders_eso[e].id
        }
      }
      platform_identity_ids = {
        eso     = azurerm_user_assigned_identity.eso_platform[c].id
        kyverno = azurerm_user_assigned_identity.kyverno[c].id
      }
    }
  }
}
