apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config
images:
  - name: acrplatformi3aldz.azurecr.io/apps/workorders/ui-server
    newTag: "2.5.759"
  - name: acrplatformi3aldz.azurecr.io/apps/workorders/worker
    newTag: "2.5.759"
  - name: acrplatformi3aldz.azurecr.io/apps/workorders/db-migrator
    newTag: "2.5.759"   # written by Octopus only
