#!/usr/bin/env bash
# Phase 0 preview: create the Octopus objects of octopus/terraform that need no Azure output, so the platform
# space shows the environments, lifecycles, projects (reading OCL from main), channels, teams and roles now.
# Details, limits and the phase-1 adoption path: docs/preview-octopus.md.
#
# Inputs (environment variables):
#   OCTOPUS_URL       Octopus Cloud URL, for example https://<instance>.octopus.app
#   OCTOPUS_API_KEY   API key of a System Manager (service accounts and custom roles need UserEdit/UserRoleEdit)
#   OCTOPUS_SPACE_ID  ID of the platform space, for example Spaces-123
#   STATE_DIR         Existing directory OUTSIDE this repo; receives octopus-preview.tfstate
#   TF_BIN            Terraform 1.7 or later
#   PLAN_ONLY=1       Optional: plan and summarise, apply nothing
#
# What it does:
#   1. Copies octopus/terraform to a temporary directory and adds a local-backend override (state in STATE_DIR).
#   2. Finds the hand-made environment infra-nonprod by name through the REST API and imports it.
#   3. Finds the Default channel that Octopus creates with project workorders and imports it (second pass on the
#      first run, because the project must exist first).
#   4. Runs terraform init and plan/apply with -target for exactly the approved resources, then refuses to apply
#      if the plan touches anything else.
# The API key reaches curl and Terraform through stdin and TF_VAR_octopus_api_key, never through arguments.

set -euo pipefail

die() { echo "apply-preview: $*" >&2; exit 1; }

: "${OCTOPUS_URL:?OCTOPUS_URL is not set}"
: "${OCTOPUS_API_KEY:?OCTOPUS_API_KEY is not set}"
: "${OCTOPUS_SPACE_ID:?OCTOPUS_SPACE_ID is not set}"
: "${STATE_DIR:?STATE_DIR is not set}"
: "${TF_BIN:?TF_BIN is not set}"
command -v curl >/dev/null || die "curl is required"
command -v python3 >/dev/null || die "python3 is required"
[ -x "$TF_BIN" ] || TF_BIN="$(command -v "$TF_BIN" || true)"
[ -n "$TF_BIN" ] && [ -x "$TF_BIN" ] || die "TF_BIN is not an executable Terraform"

plan_only="${PLAN_ONLY:-0}"
octopus_url="${OCTOPUS_URL%/}"
space_id="$OCTOPUS_SPACE_ID"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
tf_source="$repo_root/octopus/terraform"
tfvars="$script_dir/preview.tfvars"
[ -d "$tf_source" ] || die "missing $tf_source"
[ -f "$tfvars" ] || die "missing $tfvars"

[ -d "$STATE_DIR" ] || die "STATE_DIR $STATE_DIR does not exist"
state_dir="$(cd "$STATE_DIR" && pwd -P)"
case "$state_dir/" in
    "$(cd "$repo_root" && pwd -P)"/*) die "STATE_DIR must be outside the repository" ;;
esac
state_file="$state_dir/octopus-preview.tfstate"

work_dir="$(mktemp -d)"
cleanup() { rm -rf "$work_dir"; }
trap cleanup EXIT

# --- Octopus REST lookups (GET only) -------------------------------------------------------------------------

octopus_get() {
    # $1: path below /api/<space>/ including the query string. Prints the JSON body.
    printf 'header = "X-Octopus-ApiKey: %s"\n' "$OCTOPUS_API_KEY" |
        curl --config - --fail --silent --show-error --max-time 30 \
            --header "Accept: application/json" "$octopus_url/api/$space_id/$1"
}

# Prints the Id of the single item whose Name equals $1 in a paged Octopus collection read from stdin.
exact_id() {
    python3 -c '
import json, sys
name = sys.argv[1]
items = [i for i in json.load(sys.stdin).get("Items", []) if i.get("Name") == name]
if len(items) > 1:
    sys.exit("more than one item named " + name)
print(items[0]["Id"] if items else "")
' "$1"
}

infra_nonprod_id="$(octopus_get "environments?partialName=infra-nonprod&take=100" | exact_id infra-nonprod)"
[ -n "$infra_nonprod_id" ] || die "environment infra-nonprod was not found in $space_id (it must exist before the preview)"
echo "infra-nonprod: $infra_nonprod_id (imported, not recreated)"

default_channel_id() {
    local project_id
    project_id="$(octopus_get "projects?partialName=workorders&take=100" | exact_id workorders)"
    [ -n "$project_id" ] || return 0
    octopus_get "projects/$project_id/channels?take=100" | exact_id Default
}

# --- Working copy -------------------------------------------------------------------------------------------

cp "$tf_source"/*.tf "$work_dir"/
cp "$tfvars" "$work_dir/preview.auto.tfvars"

# Phase 0 creates both projects database-backed. Converting a project to version control makes Octopus commit
# its initial OCL to the default branch, and main is protected (and already holds the reviewed OCL). Phase 1
# converts them; see docs/preview-octopus.md.
python3 - "$work_dir/projects.tf" <<'PY'
import re, sys
path = sys.argv[1]
text = open(path).read()
text = re.sub(r"\n  git_library_persistence_settings \{.*?\n  \}\n", "\n", text, flags=re.S)
open(path, "w").write(text)
PY
cat > "$work_dir/backend_override.tf" <<HCL
# Generated by apply-preview.sh: local state outside the repository for the phase 0 preview.
terraform {
  backend "local" {
    path = "$state_file"
  }
}
HCL
cat > "$work_dir/imports_preview.tf" <<HCL
# Generated by apply-preview.sh: adopt the hand-made environment instead of creating a duplicate.
import {
  to = octopusdeploy_environment.this["infra-nonprod"]
  id = "$infra_nonprod_id"
}
HCL

export TF_VAR_octopus_url="$octopus_url"
export TF_VAR_octopus_space_id="$space_id"
export TF_VAR_octopus_api_key="$OCTOPUS_API_KEY"
export TF_IN_AUTOMATION=1

tf() { "$TF_BIN" -chdir="$work_dir" "$@"; }

tf init -input=false -no-color >/dev/null
echo "terraform init: done (state: $state_file)"

# --- Approved resources -------------------------------------------------------------------------------------

base_targets=(
    'octopusdeploy_environment.this["tdd"]'
    'octopusdeploy_environment.this["uat"]'
    'octopusdeploy_environment.this["prod"]'
    'octopusdeploy_environment.this["infra-nonprod"]'
    'octopusdeploy_environment.this["infra-prod"]'
    'octopusdeploy_lifecycle.workorders_standard'
    'octopusdeploy_lifecycle.workorders_hotfix'
    'octopusdeploy_lifecycle.workorders_infrastructure'
    'octopusdeploy_project_group.work_orders'
    'octopusdeploy_library_variable_set.workorders_environment'
    'octopusdeploy_library_variable_set.workorders_infrastructure'
    'octopusdeploy_project.workorders'
    'octopusdeploy_project.workorders_infrastructure'
    # octopusdeploy_channel.hotfix is phase 1: its version rules name steps that exist only in the Git-backed process.
    'octopusdeploy_docker_container_registry.docker_hub'
    'octopusdeploy_project_deployment_freeze.prod_weekend'
    'octopusdeploy_user_role.ci_release_publisher'
    'octopusdeploy_user_role.workorders_approver'
    'octopusdeploy_team.this'
    'octopusdeploy_scoped_user_role.this'
    'octopusdeploy_user.svc_codefresh_release'
    'octopusdeploy_user.svc_argocd_gateway'
)

# SKIP_SYSTEM_OBJECTS=1 leaves out users, custom user roles, teams and scoped roles. They need System Manager
# rights (UserEdit, UserRoleEdit); a Space Manager key creates everything else.
if [ "${SKIP_SYSTEM_OBJECTS:-0}" = "1" ]; then
    kept=()
    for t in "${base_targets[@]}"; do
        case "$t" in
            octopusdeploy_user_role.*|octopusdeploy_team.*|octopusdeploy_scoped_user_role.*|octopusdeploy_user.*) ;;
            *) kept+=("$t") ;;
        esac
    done
    base_targets=("${kept[@]}")
fi

# Every planned change must belong to one of these resource addresses (instances included).
allowed_prefixes='octopusdeploy_environment.this
octopusdeploy_lifecycle.workorders_standard
octopusdeploy_lifecycle.workorders_hotfix
octopusdeploy_lifecycle.workorders_infrastructure
octopusdeploy_project_group.work_orders
octopusdeploy_library_variable_set.workorders_environment
octopusdeploy_library_variable_set.workorders_infrastructure
octopusdeploy_project.workorders
octopusdeploy_project.workorders_infrastructure
octopusdeploy_channel.hotfix
octopusdeploy_channel.default
octopusdeploy_docker_container_registry.docker_hub
octopusdeploy_project_deployment_freeze.prod_weekend
octopusdeploy_user_role.ci_release_publisher
octopusdeploy_user_role.workorders_approver
octopusdeploy_team.this
octopusdeploy_scoped_user_role.this
octopusdeploy_user.svc_codefresh_release
octopusdeploy_user.svc_argocd_gateway'

run_pass() {
    # $1: pass label; $2: Default channel ID or empty.
    local label="$1" channel_id="$2" plan_file="$work_dir/$1.tfplan"
    local targets=("${base_targets[@]}")
    if [ -n "$channel_id" ]; then
        export TF_VAR_default_channel_import_id="$channel_id"
        targets+=('octopusdeploy_channel.default[0]')
        echo "Default channel of workorders: $channel_id (imported)"
    else
        unset TF_VAR_default_channel_import_id
    fi
    local target_args=()
    local t
    for t in "${targets[@]}"; do target_args+=("-target=$t"); done

    tf plan -input=false -no-color "${target_args[@]}" -out="$plan_file"
    tf show -json "$plan_file" > "$work_dir/$label.json"
    ALLOWED="$allowed_prefixes" python3 - "$work_dir/$label.json" "$label" <<'PY'
import json, os, sys
allowed = os.environ["ALLOWED"].split("\n")
plan = json.load(open(sys.argv[1]))
counts, bad = {}, []
for rc in plan.get("resource_changes", []):
    if rc.get("mode") != "managed":
        continue
    actions = rc["change"]["actions"]
    importing = bool(rc["change"].get("importing"))
    if actions == ["no-op"] and not importing:
        continue
    base = rc["address"].split("[")[0]
    if base not in allowed:
        bad.append(rc["address"])
    key = ("import+" if importing else "") + "/".join(actions)
    counts[key] = counts.get(key, 0) + 1
    if "delete" in actions:
        bad.append(rc["address"] + " (delete)")
print(f"[{sys.argv[2]}] planned changes: " + (", ".join(f"{k}={v}" for k, v in sorted(counts.items())) or "none"))
if bad:
    sys.exit("refusing: plan touches resources outside the preview or deletes: " + ", ".join(bad))
PY
    if [ "$plan_only" = "1" ]; then
        echo "[$label] PLAN_ONLY=1: nothing applied"
        return 0
    fi
    tf apply -input=false -no-color "$plan_file"
}

# Channels are phase 1: their version rules name steps that exist only in the Git-backed process, so Octopus
# rejects them on a database-backed project. MANAGE_CHANNELS=1 re-enables the Default channel import and update.
first_channel_id=""
if [ "${MANAGE_CHANNELS:-0}" = "1" ]; then first_channel_id="$(default_channel_id)"; fi
run_pass pass1 "$first_channel_id"

if [ "${MANAGE_CHANNELS:-0}" = "1" ] && [ "$plan_only" != "1" ] && [ -z "${TF_VAR_default_channel_import_id:-}" ]; then
    channel_id="$(default_channel_id)"
    [ -n "$channel_id" ] || die "project workorders exists but its Default channel was not found"
    run_pass pass2 "$channel_id"
fi

if [ "${MANAGE_CHANNELS:-0}" = "1" ] && [ "$plan_only" = "1" ] && [ -z "${TF_VAR_default_channel_import_id:-}" ]; then
    echo "Note: project workorders does not exist yet, so the Default channel import is planned on the real run (pass 2)."
fi
echo "Done. State: $state_file (keep it; phase 1 migrates it, docs/preview-octopus.md)."
