using Platform.Conformance.Harness;
using Platform.Conformance.Report;
using static Platform.Conformance.Offline.Support.Catalogues;

namespace Platform.Conformance.Offline.Report;

/// <summary>Proves the rendering of the catalogue into docs/capabilities.md.</summary>
[TestFixture]
[Category(Categories.Offline)]
public class CatalogueMarkdownRendererTests
{
    [Test]
    [Capability("CAP-HARNESS-012")]
    public void WhenRender_CatalogueWithThreeOwners_WritesOneTablePerOwnerInCatalogueOrder()
    {
        var catalogue = Parse(
            Entry("CAP-HARNESS-901", "Platform.Conformance.Offline.SampleTests.WhenA_B_C"),
            Entry("CAP-WAKE-001", "Platform.Conformance.Tests.Wake.WakeTests.WhenWake_Sleeping_Runs", live: true, destructive: true, owner: "octopus", tier: "nonprod"),
            Entry("CAP-CI-001", "Platform.Conformance.Tests.Ci.CiTests.WhenPush_Branch_Builds", live: true, owner: "codefresh", tier: "build"));

        var markdown = CatalogueMarkdownRenderer.Render(catalogue);

        markdown.ShouldStartWith("<!-- Generated by `Platform.Conformance.Report render-catalogue`");
        markdown.ShouldContain("# Platform capabilities");
        markdown.ShouldContain("The catalogue lists 3 capabilities: 2 proven by live tests, 1 offline, 1 destructive.");
        markdown.ShouldContain("| [octopus](#octopus) | 1 | 1 | 0 | 1 |");
        markdown.IndexOf("## codefresh", StringComparison.Ordinal).ShouldBeLessThan(markdown.IndexOf("## octopus", StringComparison.Ordinal));
        markdown.IndexOf("## octopus", StringComparison.Ordinal).ShouldBeLessThan(markdown.IndexOf("## platform", StringComparison.Ordinal));
        markdown.ShouldContain("| CAP-WAKE-001 | Capability CAP-WAKE-001 holds | nonprod | live, destructive | design/platform-design.md | a unit test | `WakeTests.WhenWake_Sleeping_Runs` |");
        markdown.ShouldContain("| CAP-HARNESS-901 | Capability CAP-HARNESS-901 holds | all | offline: static by nature |");
        markdown.ShouldContain("| `test-catalogue.yaml` | 3 |");
    }

    [Test]
    [Capability("CAP-HARNESS-012")]
    public void WhenRender_StatementWithPipeAndNewline_KeepsTheTableIntact()
    {
        var yaml = "capabilities:" + Environment.NewLine + Entry("CAP-PIPE-001", OfflineTest).Replace("statement: Capability CAP-PIPE-001 holds", "statement: \"Blue | green\\nrollout\"", StringComparison.Ordinal);
        var catalogue = Platform.Conformance.Harness.Catalogue.CapabilityCatalogue.Parse(yaml, "pipe.yaml");

        var markdown = CatalogueMarkdownRenderer.Render(catalogue);

        markdown.ShouldContain("| CAP-PIPE-001 | Blue \\| green rollout | all |");
    }

    [Test]
    [Capability("CAP-HARNESS-012")]
    public void WhenRender_SameCatalogueTwice_ProducesIdenticalText()
    {
        var catalogue = Parse(Entry("CAP-SAMPLE-001", OfflineTest), Entry("CAP-SAMPLE-002", LiveTest, live: true, owner: "azure"));

        var first = CatalogueMarkdownRenderer.Render(catalogue);
        var second = CatalogueMarkdownRenderer.Render(catalogue);

        second.ShouldBe(first);
    }
}
